### ISSUE TITLE
Some tif images don't include pixel size information in their tags.

### ISSUE THREAD

**Issue by ZhenhongDu** [sakoho81/miplib#3]
Some tif images don't include pixel size information in their tags.I have to assign a value to their ‘spacing’ attribute.But that's not accurate and it doesn't work well.I'd be happy if you had a good solution.Thank you！

**Comment by sakoho81** [comment]
Hi there. Yes, that's actually intended behaviour, as I always want the images to have a pixel size. That's because all the image registration functions, spatial transformations, FRC etc. work on physical units.  One can of course think of assigning a default value, like ones, if suitable tags are not found, but that may result into problems. I would recommend opening the offending images on Fiji and setting their pixel size proprely.

**Comment by ZhenhongDu** [comment]
> 
> 
> Hi there. Yes, that's actually intended behaviour, as I always want the images to have a pixel size. That's because all the image registration functions, spatial transformations, FRC etc. work on physical units. One can of course think of assigning a default value, like ones, if suitable tags are not found, but that may result into problems. I would recommend opening the offending images on Fiji and setting their pixel size proprely.

Thanks for your reply.
